// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-micro/microwire"
	"github.com/go-micro/microwire/broker"
	"github.com/go-micro/microwire/registry"
	"github.com/go-micro/microwire/transport"
	"github.com/go-micro/microwire/wire"
	"github.com/urfave/cli/v2"
	"go-micro.dev/v4"
)

import (
	_ "github.com/go-micro/plugins/v4/broker/nats"
	_ "github.com/go-micro/plugins/v4/registry/nats"
	_ "github.com/go-micro/plugins/v4/transport/nats"
)

// Injectors from wire.go:

func myApp(opts ...wire.Option) (*cli.App, error) {
	initializeServiceFunc := ProvideMyServiceInitializer()
	options := wire.ProvideOptions(opts, initializeServiceFunc)
	internalFlags := wire.ProvideMyFlags(options)
	app := wire.ProvideApp(options, internalFlags)
	return app, nil
}

func myService(ctx *cli.Context, opts *wire.Options) (micro.Service, error) {
	brokerOptions := ProvideMyBrokerOpts(opts, ctx)
	brokerBroker, err := broker.Provide(brokerOptions)
	if err != nil {
		return nil, err
	}
	registryOptions := ProvideMyRegistryOpts(opts, ctx)
	registryRegistry, err := registry.Provide(registryOptions)
	if err != nil {
		return nil, err
	}
	transportOptions := ProvideMyTransportOpts(opts, ctx)
	transportTransport, err := transport.Provide(transportOptions)
	if err != nil {
		return nil, err
	}
	v := microwire.ProvideDefaultMicroOpts(opts, brokerBroker, registryRegistry, transportTransport)
	service := wire.ProvideMicroService(opts, ctx, v)
	return service, nil
}
