// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-micro/microwire/broker"
	"github.com/go-micro/microwire/microwire"
	"github.com/urfave/cli/v2"
	"go-micro.dev/v4"
)

import (
	_ "github.com/go-micro/plugins/v4/broker/nats"
	_ "github.com/go-micro/plugins/v4/registry/nats"
	_ "github.com/go-micro/plugins/v4/transport/nats"
)

// Injectors from wire.go:

func myApp(opts ...microwire.Option) (*cli.App, error) {
	initializeServiceFunc := ProvideMyServiceInitializer()
	options := microwire.ProvideOptions(opts, initializeServiceFunc)
	internalFlags := microwire.ProvideMyFlags(options)
	app := microwire.ProvideApp(options, internalFlags)
	return app, nil
}

func myService(ctx *cli.Context, opts *microwire.Options) (micro.Service, error) {
	brokerOptions := ProvideMyBrokerOpts(opts, ctx)
	brokerBroker, err := broker.ProvideBroker(brokerOptions)
	if err != nil {
		return nil, err
	}
	v := microwire.ProvideDefaultMicroOpts(opts, brokerBroker)
	service := microwire.ProvideMicroService(opts, ctx, v)
	return service, nil
}
